### ISSUE TITLE
Error when calling attachDevice

### ISSUE THREAD

**Issue by bocajspear1** [hooklift/node-libvirt#30]
I am getting the following error with a nodejs crash when calling domain.attachDevice:

```
#
# Fatal error in ../deps/v8/src/api.h, line 297
# CHECK(allow_empty_handle || that != __null) failed
#
```

This gist contains the full stack trace:
https://gist.github.com/bocajspear1/b40f92685e8a0b8b5b3a

When the line calling attachDevice is commented out, all other calls using the current domain work properly.

NodeJS version: v0.10.26

Thanks.

**Comment by mbroadst** [comment]
I think it's probably safe to say with the multiple nan refactorings that this is no longer an issue
