### ISSUE TITLE
error when i register function callbacks for domain events

### ISSUE THREAD

**Issue by zhenfdfs** [hooklift/node-libvirt#36]
I want my ios app receive the event of my virtual machine, so i need to monitor all the event.  But I encounter an issue when I use  this function registerDomainEvent .Could anyone help me? Very thanks! 

[root@TEST-LC-NC-0-0-31 ~]# node event_cb.js
libvirt: Remote Driver error : adding cb to list

/root/event_cb.js:14
hyper.registerDomainEvent(event);
      ^
[object Error]
[root@TEST-LC-NC-0-0-31 ~]#

My code as follows:

  1 var libvirt = require('libvirt');
  2
  3 var Hypervisor = libvirt.Hypervisor;
  4 var hyper = new Hypervisor('qemu:///system');
  5
  6 var domain = hyper.lookupDomainById(173);
  7
  8 var event = { 'evtype': hyper.VIR_DOMAIN_EVENT_ID_REBOOT ,
  9                 'domain':domain,
 10               'callback': function(hyp, dom, data) {
 11                         console.log('callback');
 12               }
 13             };
 14 hyper.registerDomainEvent(event);

**Comment by atoy40** [comment]
First , you've to call libvirt.setupEvent() to start the event loop handling.
Then here is an example i'm using :

libvirt.setupEvent();

// self.connection is an Hypervisor instance.
self.connection.registerDomainEvent({evtype: self.connection.VIR_DOMAIN_EVENT_ID_LIFECYCLE, callback: function(hv, dom, data) {
    console.log("[virt] state change "+ data.evtype + " " + data.detail);
    var id = dom.getUUID();

    switch(data.evtype) {
      case 0: // defined
        break;
      case 1: // undef
        break;
      case 2: // started
        break;
      case 5:
          break;
      default:
        break;
    }
  }});

Hope it helps

Anthony.

**Comment by mbroadst** [comment]
closing as it is no longer relevant to the current codebase/implementation. Will reopen if @zhenfdfs chimes in
