### ISSUE TITLE
Use https://github.com/c4milo/node-xml2json to avoid users to mess up with xml

### ISSUE THREAD

**Issue by c4milo** [hooklift/node-libvirt#5]

**Comment by zxlin** [comment]
It doesn't look like this was ever implemented. But this would be a really nice feature to have.

**Comment by mbroadst** [comment]
@zxlin this would be very simple to implement, if you'd like to take a stab at doing this I would be more than willing to help you do it

**Comment by Rush** [comment]
While I do use xml2json (xml2js) library in my own project I do see that it opens another can of worms. JSON <-> XML conversion is not really 1:1, especially when arrays and numbers are involved. I advise against integrating such library into node-libvirt.

**Comment by mbroadst** [comment]
agreed, we'll close this for now pending future interest
