### ISSUE TITLE
lookupDomainById returns empty object

### ISSUE THREAD

**Issue by soichih** [hooklift/node-libvirt#64]
I have a running domain on my KVM.

```
hayashis@soichi7:~/test/nodejs $ sudo virsh list --all
 Id    Name                           State
----------------------------------------------------
 6     ubuntu14                       running
```

which I can query via the listActiveDomains

```
    hypervisor_object.listActiveDomains(function(err, info) {
        console.log(info);
    });
```

```
[ 6 ]
```

However, when I try to query by the id

```
    hypervisor_object.listActiveDomains(function(err, info) {
        info.forEach(function(id) {
            console.log("quering "+id);
            hypervisor_object.lookupDomainById(id, function(err, domain) {
                console.dir(err);
                console.dir(domain);
            });
        });
    });
```

I get empty object from lookupDomainById

```
quering 6
null
{}
```

I also get an empty object if I do lookupDomainByName("ubuntu14")...

What am I missing?

**Comment by jra11** [comment]
Almost the same for me:

```
/tmp# virsh -c qemu:///system list --all
 Id    Name                           State
----------------------------------------------------
 15    Browsing2                      running
```

JS code:
```
test();
function test() {
	virt = libvirt.Hypervisor('qemu:///system');
	virt.connect(function(err) {
		if (err) { return; }
		virt.listActiveDomains(function(err, activeDomains) {
			activeDomains.forEach(function(domainId) {
				console.log("Looking for "+domainId);
				virt.lookupDomainById(domainId, function(err, domain) {
					console.log(err);
					console.log(domain);
				});
			});
		});
	});
}
```
Result:
```
Looking for 15
null
{ _parent:
   { uri: 'qemu:///system',
     username: '',
     password: '',
     readOnly: false } }
```

**Comment by mbroadst** [comment]
@jra11 can you try just directly looking it up without using the loop? We have a test that runs to validate that this works correctly with the test driver, but we'll need to narrow down what's happening in your case. So you'd have:

```
var libvirt = require('libvirt');
function test() {
   var hv = new libvirt.Hypervisor('qemu:///system');
   return hv.connectAsync()
     .then(() => hv.lookupDomainById(15))
     .then((domain) => { console.log(domain); });
}

test();
```

**Comment by jra11** [comment]
@mbroadst 

Sorry I deleted my message before viewing your answer. My code was working well. 

The disturbing part was the "console.log(domain)", which prints a weird object (the "_parent" stuff without any other property, how to explain that?),  but all methods called on this domain object worked well, such as domain.destroy(...) etc.

**Comment by jra11** [comment]
For others: 

console.log on a valid Domain object prints that:
{ _parent: 
   { uri: 'qemu:///system',
     username: '',
     password: '',
     readOnly: false } }

This is how a Domain object appears in console.log, on nodeJS server-side.

**Comment by mbroadst** [comment]
@jra11 ah yes, that's a side-effect of the way we bind to libvirt and sort of a holdover from the original implementation.

That `_parent` object is a solution we came up with rather recently to ensure child objects are properly cleaned up in order with their parent objects (in this case the domain is a child of the top level hypervisor object) - memory management is a bit tricky when you're mixing C++ with javascript here. 

The reason that your domain object isn't full of all the properties you might expect to be there is the holdover from the original implementation: we basically do a 1-1 mapping with the libvirt API. This means that the object that's returned to you is essentially a wrapper around a handle for that domain object, as well as methods that allow you to retrieve information about that handle. You can think of this as a "non eager" strategy for libvirt data, and I totally agree with you that from a users perspective this seems not very ideal as you expect to see all sorts of data associated with that domain immediately.

I think this warrants some discussion with the community. When you have a Domain object, for instance, you can call e.g. `getName` on it, but I imagine your expectation was to lookup that domain, and be able to immediately do a `console.log(domain.name);` and see it. That would require that during the lookup process, we then simultaneously kick off a number of other requests on that object to populate it.

/cc @c4milo @Rush others?

**Comment by c4milo** [comment]
The main reason the domain object is not automatically populated, upon look up, is efficiency. As, it may require multiple I/O operations, depending on the hypervisor. So, it is better to let users get the specific information on demand.

**Comment by c4milo** [comment]
@mbroadst, perhaps we should also make the `_parent` property not enumerable?

**Comment by mbroadst** [comment]
@c4milo yeah that's a very good idea

**Comment by jra11** [comment]
User view as I don't have your expertise: 
a short section in the doc and a function to populate one full object in case of need would be welcomed Indeed It is really tricky as such dynamic behaviour is not usual for JS developers, and as the library is already not easy to use (you have to read the code and read the libvirt api, which is itself not very easy), being able to prefetch the full object to print it if needed would be perfect :-)

**Comment by mbroadst** [comment]
I'm basically of a mind (given time, and resources), that a top-level configuration option on the initial library import for "eager loading" should be provided. It's sometimes very silly how long a promise chain needs to be in order to get the data you want to work with, the module as is is very "low level".

I can definitely see the benefit in making it much more user friendly, with an opt-out for the performance wary. It's also worth noting that no benchmarking has been done to actually observe the penalty for an eager load. Having said that, we also need to determine WHAT data should be eagerly loaded for these types.

**Comment by soichih** [comment]
Can someone explain (in a laymen's term) what's being discussed here? Is it even related to the issue I reported at the top?

**Comment by mbroadst** [comment]
@soichih can you please try your test again with the latest codebase? I suspect the issue you're running into is because the object "looks" empty, but is in fact a useable interface to the domain.
