### ISSUE TITLE
lookupStorageVolumeByVolume is not implemented

### ISSUE THREAD

**Issue by Rush** [hooklift/node-libvirt#70]
Such a useful method and it's bummer it's not done.  Is there a similar method in the codebase we could base `lookupStorageVolumeByVolume` on?

**Comment by mbroadst** [comment]
@Rush I don't actually see that in the api reference, though I do see `virStoragePoolLookupByVolume` did you mean that?

You should be able to use the `NLV_LOOKUP_BY_VALUE_WORKER` but will probably have to fill in the implementation yourself since you'll need to unwrap a passed in `StorageVolume` object iiuc.

**Comment by Rush** [comment]
Yes I meant https://libvirt.org/html/libvirt-libvirt-storage.html#virStoragePoolLookupByVolume

> but will probably have to fill in the implementation yourself since you'll need to unwrap a passed in StorageVolume object iiuc.

That's what I ask for. Are there any similar implementations in the code that I could just copy and paste? :) I feel like each time I do Nan+v8 I need to learn it from the start.

**Comment by mbroadst** [comment]
Yeah I feel your pain :)

Unfortunately there isn't anything you can directly copy, as all of the other `lookupBy*` methods generally take a string, but I don't think what you're asking for would be too hard.

The first thing I would do if I were you would be to copy and paste the implementation for `virStoragePoolLookupByVolume` (in `storage_pool.h/cpp`), rename it to `ByVolume` but still taking a string. At that point you simply need to "unwrap" the macros, replacing the macros with the actual code and switch out the use of strings for the storage volume handle that's passed to the function, in particular here: https://github.com/hooklift/node-libvirt/blob/master/src/storage_pool.cc#L71. 

If you get some basic code for this together I can help walk you through it.

**Comment by mbroadst** [comment]
@Rush looks like you implemented this a day ago :) closing
