### ISSUE TITLE
Error with connection pointers

### ISSUE THREAD

**Issue by RiadVargas** [hooklift/node-libvirt#85]
Hello,

I'm passing by some troubles with 'defineDomain', 'createDomain' and 'lookupDomainByName'. When I execute that functions I get error like this:
`libvirt:  error : invalid connection pointer in virGetDomain
libvirt:  error : invalid connection pointer in virDomainLookupByName
lookupDomain.start(function(err, result) {
                 ^
TypeError: Object #<Hypervisor> has no method 'start' at index.js:14:18
`
I took a look at source code but didn't find anything useful.
Any ideas?

**Comment by mbroadst** [comment]
@RiadVargas are you actually connecting to the hypervisor before calling those methods? Can you please provide an example of the code that is giving you trouble?

**Comment by RiadVargas** [comment]
Hello, @mbroadst,

Yes, I'm calling that functions inside the connect callback. The strange is that the VM is created and started, when I use createDomain, but the error shows up.
Errors: http://pastebin.com/yV8zrnGm
Code: http://pastebin.com/GbbAswUE

**Comment by mbroadst** [comment]
@RiadVargas in your `connect` callback you are making two asynchronous calls at the same time: one to `createDomain` and one to `disconnect`. I suspect that the issue you are having is because you've already disconnected by the time the async worker actually attempts to create the domain

**Comment by RiadVargas** [comment]
Didn't noticed that, my bad. Thanks for your support!
