### ISSUE TITLE
lookupDomainByUUID 

### ISSUE THREAD

**Issue by fatihsoydan** [hooklift/node-libvirt#87]
Hello, 
I am trying to get a domain by uuid. 

``` 
hypervisor.lookupDomainByUUID('581053b6-2a12-4b20-b4a5-fc06c1d25cf5',function(e2,d2){
        console.log(e2);
        console.log(d2);
});
```

it says : 
libvirt: QEMU Driver error : Domain not found: no domain with matching uuid '35383130-3533-6236-2d32-6131322d3462'

Ok, you didn't find 35383blabla , but i didn't want this. 

Is there a typo problem in this function ?

**Comment by mbroadst** [comment]
@fatihsoydan I'm not sure what your question is here? You're trying to lookup the domain by an id that does not exist.

**Comment by fatihsoydan** [comment]
i will explain, 

i am searching "**581053b6-2a12-4b20-b4a5-fc06c1d25cf5**" but library says no domain with matching uuid '**35383130-3533-6236-2d32-6131322d3462**'

**Comment by atoy40** [comment]
@fatihsoydan @mbroadst I had the same problem this morning, and let me explain it :)
This is a problem with the usage of the libvirt api which now have two functions to lookup domain by UUID :
- virDomainLookupByUUID
- virDomainLookupByUUIDString

The first one wait for a raw UUID (an array of uchar), the second wait for the string form (a char*). The problem in the wrapper is Domain::GetUUID give you the string form, but Domain::LookupByUUID use the "raw" version of the function.

The only thing to do is to use virDomainLookupByUUIDString in the wrapper.

(if you convert your uuid string to HEX, you'll find a part of the uuid of the libvirt error)

Anthony.
